server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - Content-Type
              - Authorization
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/users/**
        - id: reservations
          uri: http://localhost:8091
          predicates:
            - Path=/api/reservations/**
        - id: services
          uri: http://localhost:8092
          predicates:
            - Path=/api/services/**
