server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/users/**
          filters:
            - AddResponseHeader=Access-Control-Allow-Origin, http://localhost:5173
            - AddResponseHeader=Access-Control-Allow-Methods, GET, POST, PATCH ,PUT, DELETE, OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type
            - AddResponseHeader=Access-Control-Allow-Credentials, true
        - id: reservations
          uri: http://localhost:8091
          predicates:
            - Path=/api/reservations/**
          filters:
            - AddResponseHeader=Access-Control-Allow-Origin, http://localhost:5173
            - AddResponseHeader=Access-Control-Allow-Methods, GET, POST, PATCH ,PUT, DELETE, OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type
            - AddResponseHeader=Access-Control-Allow-Credentials, true
        - id: services
          uri: http://localhost:8092
          predicates:
            - Path=/api/services/**
          filters:
            - AddResponseHeader=Access-Control-Allow-Origin, http://localhost:5173
            - AddResponseHeader=Access-Control-Allow-Methods, GET, POST, PATCH ,PUT, DELETE, OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type
            - AddResponseHeader=Access-Control-Allow-Credentials, true
